config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'new_signup'

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create', as: 'new_login'
  delete '/logout',  to: 'sessions#destroy'

  resources :genres

  resources :profiles, only: [:show, :edit, :update] do
    resources :likes, only: [:index]
  end

  resources :playlists do
    resources :likes, only: [:create, :destroy]
  end

  resources :artists do
    resources :albums do
      resources :songs
    end
  end

  get 'playlists/:id/songs/new', to: 'playlists#playlist_songs', as: 'playlist_songs_new'
  put 'playlists/:id/songs/:song_id/add', to: 'playlists#new_playlist_song', as: 'playlist_songs_edit'
  delete 'playlists/:id/songs/:song_id/destroy', to: 'playlists#destroy_playlist_song'
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true

  has_many :songs, dependent: :destroy
  belongs_to :genre
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :songs, dependent: :nullify
  has_many :genres, -> { distinct }, through: :albums, dependent: :nullify
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  before_save { self.name = name.capitalize }

  has_many :albums, dependent: :nullify
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :playlist
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :tag
  has_and_belongs_to_many :songs

  has_many :likes

  def self.search(search)
    where("name like ?", "%#{search}%")
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true

  belongs_to :artist
  belongs_to :album
  has_and_belongs_to_many :playlists
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :profile, dependent: :destroy

  has_many :playlists, dependent: :destroy

  has_many :likes

  before_save { self.email = email.downcase }

  validates :first_name, presence: true, length: { maximum: 50 }

  validates :last_name, presence: true, length: { maximum: 50 }

  validates :user_name, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }

            VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 3 }

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @profile = Profile.find(params[:profile_id])
    @likes = @profile.user.likes
  end

  def destroy
    @playlist = Playlist.find(params[:playlist_id])
    like = Like.find_by(:user_id => current_user.id, :playlist_id => @playlist.id)

    redirect_to playlists_path if like.nil?

    like.destroy

    redirect_to playlists_path
  end

  def create
    @playlist = Playlist.find(params[:playlist_id])
    @like = Like.new(:playlist_id => params[:playlist_id], :user_id => current_user.id)

    if @like.save

      if @playlist.user_id != current_user.id
        LikesMailer.new_like_message(@playlist.user).deliver
      end
      redirect_to playlists_path
    else
      @like.errors.full_messages do |msg|
        flash[:danger] = msg
      end
      render 'index'
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @artist = Artist.find(params[:artist_id])
    @songs = @artist.songs

  end

  def show
    @artist = Artist.find(params[:artist_id])
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @album = Album.find(params[:album_id])
    @song = Song.new(song_params)
    @song.artist = @artist
    @song.album_id = params[:album_id]

    if @song.save
      redirect_to artist_album_path(@artist, @album.id)
    else
      @song.errors.full_message do |error|
        flash[:error] = error
      end
      render 'new'
    end
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @album = Album.find(params[:album_id])
    @song = Song.new
  end

  def edit
    @artist = Artist.find(params[:artist_id])
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:artist_id])
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to artist_album_path(@artist, @album.id)
    else
      render 'edit'
    end
  end

  def destroy
    @artist = Artist.find(params[:artist_id])
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])

    @song.destroy

    redirect_to artist_album_path(@artist, @album)
  end

  private
  def song_params
    params.require(:song).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      create_profile(@user.id)

      UserMailer.welcome_message(@user).deliver

      flash[:success] = 'Account created successfully'
      redirect_to root_path
    else
      @user.errors.full_messages.each do |msg|
        flash[:danger] = msg
      end
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :user_name, :password, :password_confirmation)
  end

  def create_profile(user_id)
    Profile.create(user_id:user_id)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avataryze(name)
    as_array = name.split(' ')
    if as_array.length >= 2 then (as_array[0][0] + as_array[1][0]).upcase else name[0..1].upcase end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def is_owner(user_id)
    current_user.id == user_id
  end

  def user_liked?(playlist_id, user_id)
    Like.find_by(:playlist_id => playlist_id, :user_id => user_id) != nil
  end

  def like_id(playlist_id)
    Like.find_by(:playlist_id => playlist_id, :user_id => current_user.id)
  end

  def not_owner(playlist)
    playlist.user_id.to_i != current_user.id.to_i
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/index.html.erb
<div class="row">
  <div class="col-8">
    <h2>Likes <small class="text-muted"><%= @profile.user.first_name.capitalize %> <%= @profile.user.last_name.capitalize %></small></h2>
  </div>
  <div class="col-4 text-sm-right">
    <%= link_to "Back to Profile", profile_path(@profile), class: "btn btn btn-link" %>
  </div>
</div>

<% if @likes.empty? %>
<div class="row">
  <div class="col-8">
    <p>No Likes...</p>
  </div>
</div>
<% else %>
<div class="row">
  <div class="col-8">
    <ul class="list-unstyled">
      <% @likes.each do |list|%>
        <li class="media my-4">
          <div class="mr-3 name-as-cover-image"><%= avataryze(list.playlist.name) %></div>
          <div class="media-body">
            <p>
              <%= list.playlist.name %>
              <span class="text-muted">| <%= list.playlist.user.user_name %></span></p>
            <% if logged_in? && is_owner(list.playlist.user_id) %>
            <p>
              <%= link_to 'Edit', edit_playlist_path(list) %>
              <%= link_to 'Details', playlist_path(list) %>
              <%= link_to 'Delete', playlist_path(list), method: :delete %>
            </p>
            <% else %>
            <p>
              <%= link_to 'Details', playlist_path(list) %>
            </p>
            <% end %>
          </div>
        </li>
      <% end %>
      </ul>
  </div>
</div>
<% end %>

app/views/songs/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 offset-sm-3">
    <%= form_for [@artist, @album, @song] do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/songs/edit.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to 'Back To Artist', artist_path(@artist), class: "nav-link"  %>
  <li>
</ul>

<%= render 'form' %>

app/views/songs/index.html.erb
<div class="row">
  <div class="col-8">
    <h2><%= @artist.name %> <small class="text-muted">Songs</small></h2>
  </div>
  <div class="col-4 text-sm-right">
    <%= link_to "Back", artist_path(@artist), class: "btn btn btn-link" %>
  </div>
</div>

<br/>

<% if @songs.empty? %>
<div class="row">
  <div class="col-8">
  <p>No Songs...</p>
  </div>
</div>
<% else %>
<ul>
  <% @songs.each do |song| %>
    <li><%= song.name %></li>
  <% end %>
</ul>
<% end %>

app/views/songs/new.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to 'Back', artist_path(@artist), class: "nav-link"  %>
  <li>
</ul>

<%= render 'form' %>

app/views/songs/show.html.erb
<div class="row">
  <div class="col-8">
    <h2>Song <small class="text-muted"><%= @song.name %></small></h2>
  </div>
  <div class="col-4 text-sm-right">
    <%= link_to "Back", artist_album_songs_path(@artist, @album), class: "btn btn btn-link" %>
  </div>
</div>

<br/>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 offset-sm-3">
    <%= form_for @user, url: new_signup_path, method: :post do |f| %>

      <div class="form-group">
        <div class="row">
          <div class="col-6">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
          <div class="col-6">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :user_name %>
        <%= f.text_field :user_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <%= f.submit 'Create', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to 'Login', root_path, class: "nav-link"  %>
  <li>
</ul>

<%= render 'form' %>