config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'new_signup'

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create', as: 'new_login'
  delete '/logout',  to: 'sessions#destroy'

  resources :genres

  resources :profiles, only: [:show, :edit, :update] do
    resources :likes, only: [:index]
  end

  resources :playlists do
    resources :likes, only: [:create, :destroy]
  end

  resources :artists do
    resources :albums do
      resources :songs
    end
  end

  get 'playlists/:id/songs/new', to: 'playlists#playlist_songs', as: 'playlist_songs_new'
  put 'playlists/:id/songs/:song_id/add', to: 'playlists#new_playlist_song', as: 'playlist_songs_edit'
  delete 'playlists/:id/songs/:song_id/destroy', to: 'playlists#destroy_playlist_song'
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true

  has_many :songs, dependent: :destroy
  belongs_to :genre
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :songs, dependent: :nullify
  has_many :genres, -> { distinct }, through: :albums, dependent: :nullify
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  before_save { self.name = name.capitalize }

  has_many :albums, dependent: :nullify
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :playlist
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :tag
  has_and_belongs_to_many :songs

  has_many :likes

  def self.search(search)
    where("name like ?", "%#{search}%")
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true

  belongs_to :artist
  belongs_to :album
  has_and_belongs_to_many :playlists
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :profile, dependent: :destroy

  has_many :playlists, dependent: :destroy

  has_many :likes

  before_save { self.email = email.downcase }

  validates :first_name, presence: true, length: { maximum: 50 }

  validates :last_name, presence: true, length: { maximum: 50 }

  validates :user_name, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }

            VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 3 }

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avataryze(name)
    as_array = name.split(' ')
    if as_array.length >= 2 then (as_array[0][0] + as_array[1][0]).upcase else name[0..1].upcase end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def is_owner(user_id)
    current_user.id == user_id
  end

  def user_liked?(playlist_id, user_id)
    Like.find_by(:playlist_id => playlist_id, :user_id => user_id) != nil
  end

  def like_id(playlist_id)
    Like.find_by(:playlist_id => playlist_id, :user_id => current_user.id)
  end

  def not_owner(playlist)
    playlist.user_id.to_i != current_user.id.to_i
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="row">
    <div class="col-6 offset-3">
      <div class="alert alert-<%= key %>"><%= value %></div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Rails App', artists_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if current_page?(artists_path) %>">
          <%= link_to 'Artist', artists_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(genres_path) %>">
          <%= link_to 'Genres', genres_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(playlists_path) %>">
          <%= link_to 'Playlists', playlists_path, class: "nav-link" %>
        </li>
      </ul>
      <% if logged_in? %>
        <span class="nav-item dropdown">
          <a
            href="#"
            role="button"
            id="navbarDropdown"
            aria-haspopup="true"
            aria-expanded="false"
            data-toggle="dropdown"
            class="nav-link dropdown-toggle">
            Hello, <%= current_user.first_name.capitalize %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Profile', profile_path(current_user.id), class: "nav-link" %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Sign Out', logout_path, method: :delete, class: "nav-link" %>
          </div>
        </span>
      <% else %>
        <%= link_to 'Sign In', login_path, class: "nav-link" %>
        <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <br/>
    <% if flash.any? %>
      <%= render 'layouts/flash' %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>